// Generated by CoffeeScript 1.7.1
(function() {
  var Game, Jigsaw, Puzzle,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game = (function() {
    function Game(_arg) {
      this.name = _arg.name;
    }

    Game.prototype.play = function() {
      return console.log('Playing...');
    };

    return Game;

  })();

  Puzzle = (function(_super) {
    __extends(Puzzle, _super);

    function Puzzle() {
      return Puzzle.__super__.constructor.apply(this, arguments);
    }

    Puzzle.prototype.play = function() {
      console.log('Initializing puzzle...');
      return Puzzle.__super__.play.call(this);
    };

    return Puzzle;

  })(Game);

  Jigsaw = (function(_super) {
    __extends(Jigsaw, _super);

    function Jigsaw() {
      return Jigsaw.__super__.constructor.apply(this, arguments);
    }

    Jigsaw.prototype.play = function() {
      console.log('Initializing jigsaw...');
      return Jigsaw.__super__.play.call(this);
    };

    return Jigsaw;

  })(Puzzle);

  module.exports = {
    Game: Game,
    Puzzle: Puzzle,
    Jigsaw: Jigsaw
  };

}).call(this);
